---
- name: Start postfix
  systemd:
    name: postfix
    state: started
    enabled: yes

- name: Start sshd
  systemd:
    name: ssh
    state: started
    enabled: yes

- name: Reconfigure GitLab
  command: gitlab-ctl reconfigure

- name: Reconfigure and restart GitLab
  shell: gitlab-ctl reconfigure && gitlab-ctl restart
