apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: tls-secret
  namespace: log
spec:
  secretName: kibana-secret-prod
  dnsNames:
  - dmitri-kibana.coc09.mms-support.de
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - dmitri-kibana.coc09.mms-support.de 
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
