---
- name: Include OS family specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files: "{{ ansible_os_family }}.yml"
      skip: true

- block:
  - include_tasks: gitlab_pre.yml
  - include_tasks: gitlab_install.yml
  tags:
    - gitlab_install

- block: # Configure Gitlab
  - include_tasks: gitlab_search_config.yml
  - include_tasks: gitlab_post.yml
  tags:
    - gitlab_configure
